/**
 * @palantir/validation
 *
 * Zod-Schemas, die Backend (Request-Validierung) und Frontend (Formular-/
 * Typprüfung) gemeinsam nutzen – Pflichtenheft §3 und §4.
 *
 * Enthalten sind bisher die paket-übergreifende Basis (ID-Format, Schema zum
 * Response-Envelope) und die Frame-Schemas des Agent-Protokolls. Fachliche
 * Schemas werden zusammen mit den zugehörigen Typen aus `@palantir/contracts`
 * über eigene, kleine PRs ergänzt (CLAUDE.md §3 und §6).
 */

export { type Id, idSchema } from './common.js';
export { apiErrorBodySchema, apiResponseSchema, errorCodeSchema } from './envelope.js';
export {
  type CreateRoleInput,
  type UpdateRoleInput,
  createRoleInputSchema,
  permissionSchema,
  roleDescriptionSchema,
  roleNameSchema,
  rolePermissionsBundleSchema,
  updateRoleInputSchema,
} from './rbac.js';
export {
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  type ChangePasswordInput,
  type ConfirmTwoFactorInput,
  type DeleteAccountInput,
  type DisableTwoFactorInput,
  type LinkPasswordInput,
  type LoginInput,
  type RegisterInput,
  type TwoFactorInput,
  changePasswordInputSchema,
  confirmTwoFactorInputSchema,
  deleteAccountInputSchema,
  disableTwoFactorInputSchema,
  linkPasswordInputSchema,
  passwordResetResultSchema,
  sessionDtoSchema,
  sessionPermissionsSchema,
  totpCodeSchema,
  twoFactorSetupSchema,
  accountDtoSchema,
  accountRoleSummarySchema,
  altchaChallengeSchema,
  altchaSolutionPayloadSchema,
  authMethodTypeSchema,
  authenticatedResultSchema,
  displayNameSchema,
  globalPermissionsSchema,
  linkedAuthMethodSchema,
  loginInputSchema,
  loginResultSchema,
  loginResultStatusSchema,
  oauthProviderSchema,
  passwordSchema,
  registerInputSchema,
  twoFactorCodeSchema,
  twoFactorInputSchema,
  usernameSchema,
} from './auth.js';
export {
  agentCommandNameSchema,
  agentCommandResultFrameSchema,
  agentContainerStateSchema,
  agentContainerStatusSchema,
  agentEventFrameSchema,
  agentEventNameSchema,
  agentHelloFrameSchema,
  agentStateReportFrameSchema,
  agentToBackendFrameSchema,
  backendCommandFrameSchema,
  backendStateRequestFrameSchema,
  backendToAgentFrameSchema,
  backendWelcomeFrameSchema,
  correlationIdSchema,
  isoTimestampSchema,
} from './agent-protocol.js';
export {
  type BackupOverviewQuery,
  type CreateBackupInput,
  type CreateServerExportInput,
  type UpdateBackupScheduleInput,
  backupOverviewQuerySchema,
  backupStatusSchema,
  backupTypeSchema,
  createBackupInputSchema,
  createServerExportInputSchema,
  cronExpressionSchema,
  updateBackupScheduleInputSchema,
} from './backups.js';
export {
  type CreateHostNodeInput,
  type UpdateHostNodeInput,
  createHostNodeInputSchema,
  hostNodeNameSchema,
  hostNodeStatusSchema,
  updateHostNodeInputSchema,
  wireguardIpSchema,
} from './host-node.js';
export {
  type CreatePortRangeInput,
  type UpdatePortRangeInput,
  createPortRangeInputSchema,
  portProtocolSchema,
  portRangeLabelSchema,
  publicPortSchema,
  updatePortRangeInputSchema,
} from './address.js';
export {
  type AppendAuditEntryInput,
  type AuditLogQuery,
  appendAuditEntryInputSchema,
  auditActionSchema,
  auditLogQuerySchema,
  auditMetadataSchema,
  auditTargetTypeSchema,
} from './audit.js';
export {
  type AgentStorageEntryInput,
  type DeleteStorageEntryInput,
  type GetStorageBreakdownResult,
  type StartStorageScanInput,
  agentStorageEntryKindSchema,
  agentStorageEntrySchema,
  deleteStorageEntryInputSchema,
  getStorageBreakdownPayloadSchema,
  getStorageBreakdownResultSchema,
  startStorageScanInputSchema,
  storageEntryKindSchema,
} from './storage.js';
export {
  type ApproveRegistrationRequestInput,
  type BlockRegistrationRequestInput,
  type RegistrationRequestQuery,
  approveRegistrationRequestInputSchema,
  blockRegistrationRequestInputSchema,
  registrationRequestQuerySchema,
  registrationRequestStatusSchema,
} from './registration-request.js';
export {
  AGENT_COMMAND_PAYLOAD_SCHEMAS,
  createBackupCommandPayloadSchema,
  createBackupCommandResultSchema,
  deleteBackupCommandPayloadSchema,
  deleteBackupCommandResultSchema,
  downloadBackupCommandPayloadSchema,
  downloadBackupCommandResultSchema,
  hostPathSchema,
  restoreBackupCommandPayloadSchema,
  restoreBackupCommandResultSchema,
  sha256Schema,
  agentPortMappingSchema,
  agentResourceLimitsSchema,
  agentServerIdSchema,
  agentVolumeMountSchema,
  containerIdSchema,
  containerPathSchema,
  createCommandPayloadSchema,
  deleteCommandPayloadSchema,
  execConsoleCommandPayloadSchema,
  fileListCommandPayloadSchema,
  fileReadCommandPayloadSchema,
  fileWriteCommandPayloadSchema,
  getLogsCommandPayloadSchema,
  getStatsCommandPayloadSchema,
  restartCommandPayloadSchema,
  startCommandPayloadSchema,
  stopCommandPayloadSchema,
} from './agent-commands.js';
export {
  type CloneServerInput,
  type CreateServerInput,
  type ScheduleInput,
  type ServerMemberInput,
  type UpdateServerSettingsInput,
  cloneServerInputSchema,
  consoleCommandSchema,
  createServerInputSchema,
  gameConfigValueSchema,
  gameConfigValuesSchema,
  scheduleActionSchema,
  scheduleInputSchema,
  serverFilePathSchema,
  serverMemberInputSchema,
  serverMemberLevelSchema,
  serverNameSchema,
  serverResourceLimitsSchema,
  startupParametersSchema,
  subdomainSchema,
  updateServerSettingsInputSchema,
  worldImportInputSchema,
} from './servers.js';
export {
  type NodeResourcesInput,
  type UserResourceLimitsInput,
  cpuCoresSchema,
  megabytesSchema,
  nodeResourcesSchema,
  resourceWarningThresholdsSchema,
  serverCountSchema,
  thresholdPercentSchema,
  userResourceLimitsInputSchema,
} from './resources.js';
